-- MySQL Script generated by MySQL Workbench
-- mié 13 jun 2018 19:21:51 ART
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`MedioDePago`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MedioDePago` (
  `nombreMedioDePago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`nombreMedioDePago`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `idCliente` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `apellido` VARCHAR(45) NULL,
  `foto` VARCHAR(45) NULL,
  `domicilioFact` VARCHAR(45) NULL,
  `nombreMedioDePago` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`),
  CONSTRAINT `fk_Cliente_MedioDePago1`
    FOREIGN KEY (`nombreMedioDePago`)
    REFERENCES `mydb`.`MedioDePago` (`nombreMedioDePago`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Telefono`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Telefono` (
  `idCliente` INT NOT NULL,
  `numero` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idCliente`, `numero`),
  CONSTRAINT `idCliente`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tarjeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tarjeta` (
  `idTarjeta` INT NOT NULL,
  `activada` TINYINT(1) NOT NULL,
  `foto` VARCHAR(45) NULL,
  `idCliente` INT NOT NULL,
  PRIMARY KEY (`idTarjeta`),
  CONSTRAINT `fk_Tarjeta_Cliente1`
    FOREIGN KEY (`idCliente`)
    REFERENCES `mydb`.`Cliente` (`idCliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Factura`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Factura` (
  `fechaEmitida` DATETIME NULL,
  `fechaVencimiento` DATETIME NULL,
  `numero` INT NOT NULL AUTO_INCREMENT,
  `idTarjeta` INT NOT NULL,
  PRIMARY KEY (`numero`),
  CONSTRAINT `idTarjeta`
    FOREIGN KEY (`idTarjeta`)
    REFERENCES `mydb`.`Tarjeta` (`idTarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Recibo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Recibo` (
  `fecha` DATETIME NOT NULL,
  `numero` INT NOT NULL,
  PRIMARY KEY (`numero`),
  CONSTRAINT `fk_Recibo_Factura1`
    FOREIGN KEY (`numero`)
    REFERENCES `mydb`.`Factura` (`numero`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `idEmpresa` INT NOT NULL,
  `cuit` VARCHAR(45) NULL,
  `razonSocial` VARCHAR(45) NULL,
  `pais` VARCHAR(45) NULL,
  `direccion` VARCHAR(45) NULL,
  `provincia/Estado` VARCHAR(45) NULL,
  PRIMARY KEY (`idEmpresa`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Producto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Producto` (
  `idProducto` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `tipoProducto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idProducto`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DaAcceso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DaAcceso` (
  `idTarjeta` INT NOT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idTarjeta`, `idProducto`),
  CONSTRAINT `fk_DaAcceso_Tarjeta`
    FOREIGN KEY (`idTarjeta`)
    REFERENCES `mydb`.`Tarjeta` (`idTarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_DaAcceso_Producto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consumo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consumo` (
  `idConsumo` INT NOT NULL,
  `fechaYhora` DATETIME NULL,
  `importe` DECIMAL NULL,
  `idTarjeta` INT NOT NULL,
  `idProducto` INT NOT NULL,
  PRIMARY KEY (`idConsumo`),
  CONSTRAINT `fk_Consumo_DaAcceso`
    FOREIGN KEY (`idTarjeta` , `idProducto`)
    REFERENCES `mydb`.`DaAcceso` (`idTarjeta` , `idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `nombreCategoria` VARCHAR(45) NOT NULL,
  `x` DECIMAL NULL,
  `y` DECIMAL NULL,
  PRIMARY KEY (`nombreCategoria`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parque`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parque` (
  `idParque` INT NOT NULL,
  `nombre` VARCHAR(45) NULL,
  `ubicacion` VARCHAR(45) NULL,
  PRIMARY KEY (`idParque`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Atraccion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Atraccion` (
  `idProducto` INT NOT NULL,
  `idParque` INT NOT NULL,
  `edadDesde` INT NULL,
  `edadHasta` INT NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `idParque`
    FOREIGN KEY (`idParque`)
    REFERENCES `mydb`.`Parque` (`idParque`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Atraccion_Producto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Evento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Evento` (
  `idProducto` INT NOT NULL,
  `fechaDesde` DATETIME NULL,
  `fechaHasta` DATETIME NULL,
  `idEmpresa` INT NOT NULL,
  PRIMARY KEY (`idProducto`),
  CONSTRAINT `idEmpresa`
    FOREIGN KEY (`idEmpresa`)
    REFERENCES `mydb`.`Empresa` (`idEmpresa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Evento_Producto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Precio`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Precio` (
  `diaSemana` VARCHAR(45) NOT NULL,
  `idProducto` INT NOT NULL,
  `valor` DECIMAL NOT NULL,
  PRIMARY KEY (`diaSemana`, `idProducto`),
  CONSTRAINT `fk_Precio_Producto1`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PoseeDescuento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PoseeDescuento` (
  `nombreCategoria` VARCHAR(45) NOT NULL,
  `idProducto` INT NOT NULL,
  `descuento` FLOAT NOT NULL,
  PRIMARY KEY (`nombreCategoria`, `idProducto`),
  CONSTRAINT `nombreCategoria`
    FOREIGN KEY (`nombreCategoria`)
    REFERENCES `mydb`.`Categoria` (`nombreCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProducto`
    FOREIGN KEY (`idProducto`)
    REFERENCES `mydb`.`Producto` (`idProducto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PerteneceA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PerteneceA` (
  `idTarjeta` INT NOT NULL,
  `nombreCategoria` VARCHAR(45) NOT NULL,
  `fechaDesde` DATE NOT NULL,
  PRIMARY KEY (`idTarjeta`, `nombreCategoria`, `fechaDesde`),
  CONSTRAINT `fk_Tarjeta_has_Categoria_Tarjeta1`
    FOREIGN KEY (`idTarjeta`)
    REFERENCES `mydb`.`Tarjeta` (`idTarjeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tarjeta_has_Categoria_Categoria1`
    FOREIGN KEY (`nombreCategoria`)
    REFERENCES `mydb`.`Categoria` (`nombreCategoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

USE `mydb` ;

-- -----------------------------------------------------
-- procedure cambiarAllCategorias
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
CREATE PROCEDURE `cambiarAllCategorias` ()
BEGIN
	DECLARE v_finished INTEGER DEFAULT 0;
    DECLARE v_idTarjeta INTEGER DEFAULT 0;
    DECLARE v_conPromMensual INT DEFAULT 0;
    DECLARE v_conAcumAnual INT DEFAULT 0;
    DECLARE v_catCorresp_nombre VARCHAR(50) DEFAULT NULL;
    DECLARE v_catActual_nombre VARCHAR(50) DEFAULT NULL;
    DECLARE v_catActual_x INT DEFAULT 0;
    DECLARE v_catActual_y INT DEFAULT 0;
    DECLARE v_catCorresp_x INT DEFAULT 0;
    DECLARE v_allIdsTarjetas CURSOR FOR SELECT idTarjeta FROM Tarjeta WHERE activada = 1;
    -- De una sola query calculo el promedio mensual en el año actual y el gasto acumulado
    
	-- declare NOT FOUND handler
	DECLARE CONTINUE HANDLER FOR NOT FOUND SET v_finished = 1;

	OPEN v_allIdsTarjetas;

	for_each_idTarjeta: LOOP

        FETCH v_allIdsTarjetas INTO v_idTarjeta;
        IF v_finished = 1 THEN 	LEAVE for_each_idTarjeta; END IF;

        -- Obtengo el consumo promedio por mes y el total gastado en el anio
        SELECT SUM(importe), AVG(importe) INTO v_conAcumAnual, v_conPromMensual 
        FROM  Consumo c
        WHERE c.idTarjeta = v_idTarjeta AND YEAR(c.fechaYhora) = YEAR(CURDATE())
        GROUP BY YEAR(fechaYhora) DESC;

        -- La categoria actual es aquella que en la relacion perteneceA posee la fecha mas reciente
        SELECT  pa1.nombreCategoria, x, y INTO v_catActual_nombre , v_catActual_x , v_catActual_y 
        FROM  PerteneceA pa1, Categoria c
        WHERE pa1.nombreCategoria = c.nombreCategoria
                AND pa1.idTarjeta = v_idTarjeta
                AND pa1.fechaDesde = (SELECT MAX(pa2.fechaDesde)
                                      FROM PerteneceA pa2
                                      WHERE pa2.idTarjeta = v_idTarjeta);

        -- La categoria correspondiente va a ser aquella a la que se le haya superado el limite x
        SELECT  nombreCategoria, x
        INTO v_catCorresp_nombre , v_catCorresp_x
        FROM  Categoria
        WHERE x = (SELECT MAX(x) FROM Categoria c  WHERE c.x <= v_conAcumAnual);

        -- Si el consumo mensual es adecuado para la categoria actual, y la categoria correspondiente no es mayor a la actual, entonces la categoria correspondiente es la actual
        -- En cualquier otro caso, la categoria se resuelve por el parametro x
        IF NOT (v_catActual_y <= v_conPromMensual and v_catCorresp_x <= v_catActual_x )THEN
        	INSERT INTO PerteneceA VALUES (v_idTarjeta,v_catCorresp_nombre, CURDATE());
        END IF;

        

    END LOOP for_each_idTarjeta;
    
	CLOSE v_allIdsTarjetas;
END$$

DELIMITER ;

-- -----------------------------------------------------
-- procedure atraccionMayorVisita
-- -----------------------------------------------------

DELIMITER $$
USE `mydb`$$
create procedure atraccionMayorVisita(in fechaDesde datetime, in fechaHasta datetime)
begin
SELECT producto.nombre as ParqueAtraccion, count(*) as cantidadVisitado FROM 
mydb.Atraccion atraccion, mydb.Tarjeta tarjeta, mydb.Producto producto, mydb.Consumo consumo where
	atraccion.idProducto = producto.idProducto and 
    consumo.fechaYhora >= fechaDesde and
    consumo.fechaYhora <= fechaHasta and
    producto.idProducto = consumo.idProducto 
group by consumo.idProducto
Having count(*) >= ALL (Select count(*) as count from mydb.Atraccion atraccion, mydb.Tarjeta tarjeta, 
mydb.Producto producto, mydb.Consumo consumo where
	atraccion.idProducto = producto.idProducto and 
    consumo.fechaYhora >= fechaDesde and
    consumo.fechaYhora <= fechaHasta and
    producto.idProducto = consumo.idProducto
    group by consumo.idProducto)
;
end$$

DELIMITER ;
USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Cliente_BEFORE_INSERT` BEFORE INSERT ON `Cliente` FOR EACH ROW
BEGIN

if !(new.foto REGEXP "^http:\/\/[.A-Za-z0-9-]+.[a-zA-Z]\/") then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El atributo foto debe ser una url a una fotografia';
end if;

END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Cliente_BEFORE_UPDATE` BEFORE UPDATE ON `Cliente` FOR EACH ROW
BEGIN

if !(new.foto REGEXP "^http:\/\/[.A-Za-z0-9-]+.[a-zA-Z]\/") then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El atributo foto debe ser una url a una fotografia';
end if;

END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Factura_BEFORE_INSERT` BEFORE INSERT ON `Factura` FOR EACH ROW
BEGIN

if !(new.fechaVencimiento >= new.fechaEmitida) then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El atributo fechaVencimiento debe ser mayor a fechaEmitida';
end if;

END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Factura_BEFORE_UPDATE` BEFORE UPDATE ON `Factura` FOR EACH ROW
BEGIN

if !(new.fechaVencimiento >= new.fechaEmitida) then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El atributo fechaVencimiento debe ser mayor a fechaEmitida';
end if;

END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Empresa_BEFORE_INSERT` BEFORE INSERT ON `Empresa` FOR EACH ROW
BEGIN

if !(new.cuit REGEXP "^[0-9]{10}$") then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El atributo cuit debe estar formado por 10 digitos numericos';
end if;

END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Empresa_BEFORE_UPDATE` BEFORE UPDATE ON `Empresa` FOR EACH ROW
BEGIN

if !(new.cuit REGEXP "^[0-9]{10}$") then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El atributo cuit debe estar formado por 10 digitos numericos';
end if;

END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Producto_BEFORE_INSERT` BEFORE INSERT ON `Producto` FOR EACH ROW
BEGIN

if !(new.tipoProducto = 'evento' or new.tipoProducto = 'atraccion') then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El tipo de producto debe ser atraccion o evento';
end if;

END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Producto_AFTER_INSERT` AFTER INSERT ON `Producto` FOR EACH ROW
BEGIN
INSERT INTO `Precio` (`idProducto`, `diaSemana`, `valor`) VALUES (new.idProducto, 'D', 9999);
INSERT INTO `Precio` (`idProducto`, `diaSemana`, `valor`) VALUES (new.idProducto, 'L', 9999);
INSERT INTO `Precio` (`idProducto`, `diaSemana`, `valor`) VALUES (new.idProducto, 'M', 9999);
INSERT INTO `Precio` (`idProducto`, `diaSemana`, `valor`) VALUES (new.idProducto, 'X', 9999);
INSERT INTO `Precio` (`idProducto`, `diaSemana`, `valor`) VALUES (new.idProducto, 'J', 9999);
INSERT INTO `Precio` (`idProducto`, `diaSemana`, `valor`) VALUES (new.idProducto, 'V', 9999);
INSERT INTO `Precio` (`idProducto`, `diaSemana`, `valor`) VALUES (new.idProducto, 'S', 9999);
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Producto_BEFORE_UPDATE` BEFORE UPDATE ON `Producto` FOR EACH ROW
BEGIN

if !(new.tipoProducto = 'evento' or new.tipoProducto = 'atraccion') then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El tipo de producto debe ser atraccion o evento';
end if;

END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Categoria_BEFORE_INSERT` BEFORE INSERT ON `Categoria` FOR EACH ROW
BEGIN

if (new.x < 0 or new.y < 0) then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Los atributo x e y deben ser mayores o igual a 0';
end if;
 
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Categoria_BEFORE_UPDATE` BEFORE UPDATE ON `Categoria` FOR EACH ROW
BEGIN

if (new.x < 0 or new.y < 0) then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'Los atributo x e y deben ser mayores o igual a 0';
end if;

END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Atraccion_BEFORE_INSERT` BEFORE INSERT ON `Atraccion` FOR EACH ROW
BEGIN
if (new.edadDesde < 0 or ( new.edadDesde > new.edadHasta)) then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El atributo edadDesde debe ser menor o igual a edadHasta';
end if;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Atraccion_BEFORE_UPDATE` BEFORE UPDATE ON `Atraccion` FOR EACH ROW
BEGIN
if (new.edadDesde < 0 or ( new.edadDesde > new.edadHasta)) then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El atributo edadDesde debe ser menor o igual a edadHasta';
end if;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Evento_BEFORE_INSERT` BEFORE INSERT ON `Evento` FOR EACH ROW
BEGIN
if (new.fechaDesde > new.fechaHasta) then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El atributo fechaDesde debe ser menor o igual a fechaHasta';
end if;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Evento_BEFORE_UPDATE` BEFORE UPDATE ON `Evento` FOR EACH ROW
BEGIN
if (new.fechaDesde > new.fechaHasta) then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El atributo fechaDesde debe ser menor o igual a fechaHasta';
end if;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Precio_BEFORE_INSERT` BEFORE INSERT ON `Precio` FOR EACH ROW
BEGIN
if (new.valor < 0 or (new.diaSemana != 'L' AND 
new.diaSemana != 'M' AND
new.diaSemana != 'X' AND
new.diaSemana != 'J' AND
new.diaSemana != 'V' AND
new.diaSemana != 'S' AND
new.diaSemana != 'D')) then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El atributo VALOR debe ser mayor a 0 y diaSemana debe 
pertencer a {L,M,X,J,V,S,D}';
end if;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`Precio_BEFORE_UPDATE` BEFORE UPDATE ON `Precio` FOR EACH ROW
BEGIN
if (new.valor < 0 or (new.diaSemana != 'L' AND 
new.diaSemana != 'M' AND
new.diaSemana != 'X' AND
new.diaSemana != 'J' AND
new.diaSemana != 'V' AND
new.diaSemana != 'S' AND
new.diaSemana != 'D')) then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El atributo VALOR debe ser mayor a 0 y diaSemana debe 
pertencer a {L,M,X,J,V,S,D}';
end if;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`PoseeDescuento_BEFORE_INSERT` BEFORE INSERT ON `PoseeDescuento` FOR EACH ROW
BEGIN
if (new.descuento <= 0) then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El atributo descuento debe ser mayor a 0';
end if;
END$$

USE `mydb`$$
CREATE DEFINER = CURRENT_USER TRIGGER `mydb`.`PoseeDescuento_BEFORE_UPDATE` BEFORE UPDATE ON `PoseeDescuento` FOR EACH ROW
BEGIN
if (new.descuento <= 0) then
SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT = 'El atributo descuento debe ser mayor a 0';
end if;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
